name: Deploy Messenger App UI demo gh-pages

on:
  workflow_dispatch:
  push:
    tags: [ '*' ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter config --enable-web
        shell: bash
        working-directory: .
      - run: flutter build web --release --base-href /messenger/
        shell: bash
        working-directory: ./packages/messenger
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./packages/messenger/build/web
